"""Opportunity scoring v10.4 — manual optimization from backtest findings.

Generated by scoring_comparator.py on 2026-04-15.

Changes from v10.3:
  * Consistency: 30->40 (Spearman 0.572, strongest predictor)
  * Stability:   30->28 (Spearman 0.317)
  * Liquidity:   10->3  (Pearson -0.251, NEGATIVE correlation -> filter only)
  * Yield:       15->12 (Spearman 0.150)
  * Fee Eff:     10->4  (Pearson -0.270, NEGATIVE correlation)
  * Trend:        5->3  (Spearman 0.192, tie-breaker only)
  * Momentum penalties: accelerating -6, decelerating -8, negative -3
  * Z-penalty: more aggressive from z>0.8
  * Hard caps: reality relaxed to 2.0x (was 1.5x, backtest showed +25% APR)
  * cap_z tightened at z>2.5

Base dimensions (90 pts max):
  1. Stability       (28 pts)
  2. Consistency     (40 pts)
  3. Liquidity       ( 3 pts)
  4. Yield           (12 pts)
  5. Fee Efficiency  ( 4 pts)
  6. Trend           ( 3 pts)
"""
import math
from analysis.indicators import compute_all_indicators


def opportunity_score(params: dict) -> int:
    """Unified scoring for any arbitrage opportunity (v10.4)."""
    sc = 0

    cv = params.get("cv", 999)
    min_ratio = params.get("min_ratio", 0)
    streak = params.get("streak", 0)
    pct = params.get("pct", 0)
    volume = params.get("volume", 0)
    settlement_avg = abs(params.get("settlement_avg", 0))
    ppd = params.get("payments_per_day", 3)
    fee_drag = params.get("fee_drag", 1)
    current_rate = abs(params.get("current_rate", 0))
    rates = params.get("rates", [])

    # -- 1. STABILITY (28 pts) ------------------------------------
    if cv < 0.2 and min_ratio > 0.5:   sc += 28
    elif cv < 0.3 and min_ratio > 0.3: sc += 22
    elif cv < 0.3:                     sc += 18
    elif cv < 0.5:                     sc += 12
    elif cv < 0.8:                     sc += 7
    elif cv < 1.2:                     sc += 3
    else:                              sc += 1

    # -- 2. CONSISTENCY (40 pts) ----------------------------------
    if streak >= 12 and pct >= 90:     sc += 40
    elif streak >= 8 and pct >= 85:    sc += 32
    elif streak >= 5 and pct >= 80:    sc += 26
    elif streak >= 3 and pct >= 70:    sc += 20
    elif pct >= 60:                    sc += 12
    else:                              sc += 3

    # -- 3. LIQUIDITY (3 pts) -------------------------------------
    if volume >= 50e6:    sc += 3
    elif volume >= 20e6:  sc += 3
    elif volume >= 10e6:  sc += 2
    elif volume >= 5e6:   sc += 2
    elif volume >= 1e6:   sc += 1
    else:                 sc += 0

    # -- 4. YIELD (12 pts, non-monotonic) -------------------------
    yield_day_pct = settlement_avg * ppd * 100
    reality_penalty = False
    if settlement_avg > 0 and current_rate > settlement_avg * 2.0:
        reality_penalty = True

    if reality_penalty:
        if yield_day_pct >= 0.10:     sc += 3
        elif yield_day_pct >= 0.03:   sc += 5
        elif yield_day_pct >= 0.01:   sc += 3
        else:                         sc += 1
    else:
        if 0.03 <= yield_day_pct < 0.10:     sc += 12
        elif 0.10 <= yield_day_pct < 0.15:   sc += 9
        elif 0.01 <= yield_day_pct < 0.03:   sc += 8
        elif 0.15 <= yield_day_pct < 0.25:   sc += 4
        elif yield_day_pct >= 0.25:           sc += 1
        else:                                 sc += 1

    # -- 5. FEE EFFICIENCY (4 pts) --------------------------------
    if fee_drag < 0.1:     sc += 4
    elif fee_drag < 0.2:   sc += 3
    elif fee_drag < 0.3:   sc += 2
    elif fee_drag < 0.5:   sc += 1
    else:                  sc += 0

    # -- 6. TREND (3 pts) -----------------------------------------
    indicators = compute_all_indicators(current_rate, rates)
    mom_pts  = min(2, indicators["momentum"]["points"])
    pctl_pts = min(1, indicators["percentile"]["points"])
    sc += mom_pts + pctl_pts

    # -- 7. MOMENTUM PENALTIES ------------------------------------
    mom_signal = indicators["momentum"].get("signal", "flat")
    if mom_signal == "accelerating":
        sc -= 6
    elif mom_signal == "decelerating":
        sc -= 8
    elif mom_signal == "negative":
        sc -= 3

    # -- 8. Z-SCORE PENALTY ---------------------------------------
    z_val = indicators["z_score"].get("z", 0)
    if z_val > 3.0:       sc -= 25
    elif z_val > 2.5:     sc -= 18
    elif z_val > 2.0:     sc -= 13
    elif z_val > 1.5:     sc -= 9
    elif z_val > 1.0:     sc -= 5
    elif z_val > 0.8:     sc -= 2

    # -- 9. HARD CAPS ---------------------------------------------
    percentile = indicators["percentile"].get("percentile", 0)

    if z_val > 2.5:
        sc = min(sc, 35)
    if streak < 3 and percentile >= 80:
        sc = min(sc, 45)
    if reality_penalty:
        sc = min(sc, 55)

    params["_indicators"] = indicators
    return max(0, min(sc, 100))


def stability_grade(score: int) -> str:
    if score >= 85: return "A"
    elif score >= 70: return "B"
    elif score >= 55: return "C"
    return "D"


def estimated_hold_days(hist: dict) -> int:
    streak = hist.get("streak", 0)
    pct = hist.get("pct", 0)
    rates = hist.get("_rates", [])
    if not rates:
        return 0
    intervals_per_day = 3
    streak_days = streak / intervals_per_day
    if pct >= 90 and streak_days >= 5:
        return min(int(streak_days * 0.7), 14)
    elif pct >= 80 and streak_days >= 3:
        return min(int(streak_days * 0.5), 10)
    elif pct >= 70 and streak_days >= 1:
        return min(int(streak_days * 0.4), 7)
    elif streak_days >= 1:
        return max(1, int(streak_days * 0.3))
    return 0


def calculate_rsi(closes: list, period: int = 14) -> float:
    if len(closes) < period + 1:
        return -1
    changes = [closes[i + 1] - closes[i] for i in range(len(closes) - 1)]
    gains = [max(c, 0) for c in changes]
    losses = [abs(min(c, 0)) for c in changes]
    avg_gain = sum(gains[:period]) / period
    avg_loss = sum(losses[:period]) / period
    for i in range(period, len(gains)):
        avg_gain = (avg_gain * (period - 1) + gains[i]) / period
        avg_loss = (avg_loss * (period - 1) + losses[i]) / period
    if avg_loss == 0:
        return 100
    rs = avg_gain / avg_loss
    return 100 - (100 / (1 + rs))
